---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment 
  namespace: vaccination-system-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      vms: appointment
  template:
    metadata:
      labels:
        vms: appointment
    spec:
      containers:
        - name: appointment-service-pod
          image: 678554781153.dkr.ecr.ap-southeast-1.amazonaws.com/vaccination-system-images:appointment-service
          imagePullPolicy: Always
          env:
            - name: APP_KEY
              value: "${APP_KEY}"
            - name: APP_ENV
              value: "${APP_ENV}"
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: appointment-config
                  key: DB_PORT
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: appointment-config
                  key: DB_CONNECTION
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: appointment-config
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: appointment-config
                  key: DB_USERNAME
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
            
      
          ports:
            - containerPort: 19090
          resources:
            limits:
              cpu: 300m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 250Mi

